# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_order',
            old_name='client',
            new_name='client_id',
        ),
    ]
