# Generated by Django 2.1.2 on 2018-10-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20181023_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='mail',
            new_name='email',
        ),
    ]
