# Generated by Django 2.1.2 on 2018-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20181023_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
