# Generated by Django 2.1.2 on 2018-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20181024_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale_order',
            name='date',
            field=models.DateField(),
        ),
    ]
