# Generated by Django 2.1.2 on 2018-10-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20181024_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
