# Generated by Django 2.1.2 on 2018-10-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20181024_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='supplier',
            field=models.ForeignKey(choices=[(6, 'Supplier BoBi'), (7, 'Supplier2')], on_delete=django.db.models.deletion.CASCADE, to='deal.Supplier'),
        ),
    ]
