# Generated by Django 2.1.2 on 2018-10-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20181025_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Supplier'),
        ),
    ]
